name: Build and Upload Android APK

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t miqt/android:latest -f docker/android-armv8a-go1.23-qt5.15-dynamic.Dockerfile .

      - name: Build .so file
        run: |
          docker run --rm -v $(pwd):/src -w /src miqt/android:latest go build -buildmode c-shared -ldflags "-s -w -extldflags -Wl,-soname,my_go_app.so" -o android-build/libs/arm64-v8a/my_go_app.so

      - name: Build Qt linking stub
        run: |
          docker run --rm -v $(pwd):/src -w /src miqt/android:latest cmd/android-stub-gen/android-stub-gen.sh my_go_app.so AndroidMain android-build/libs/arm64-v8a/libRealAppName_arm64-v8a.so

      - name: Build androiddeployqt configuration file
        run: |
          docker run --rm -v $(pwd):/src -w /src miqt/android:latest cmd/android-mktemplate/android-mktemplate.sh RealAppName deployment-settings.json

      - name: Build Android package
        run: |
          docker run --rm -v $(pwd):/src -w /src miqt/android:latest androiddeployqt --input ./deployment-settings.json --output ./android-build/

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: android-build-debug.apk
          path: android-build/build/outputs/apk/debug/android-build-debug.apk
